#!/bin/sh

# i-MSCP a internet Multi Server Control Panel
#
# Copyright (C) 2006-2010 by isp Control Panel - http://ispcp.net
# Copyright (C) 2010 by internet Multi Server Control Panel - http://i-mscp.net
#
# Version: $Id: imscp_network 4925 2011-07-13 23:14:46Z nuxwin $
#
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.mozilla.org/MPL/
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
# License for the specific language governing rights and limitations
# under the License.
#
# The Original Code is "ispCP ω (OMEGA) a Virtual Hosting Control Panel".
#
# The Initial Developer of the Original Code is ispCP Team.
# Portions created by Initial Developer are Copyright (C) 2006-2010 by
# isp Control Panel. All Rights Reserved.
#
# Portions created by the i-MSCP Team are Copyright (C) 2010 by
# internet Multi Server Control Panel. All Rights Reserved.
#
# The i-MSCP Home Page is:
#
#    http://i-mscp.net
#

### BEGIN INIT INFO
# Provides:             imscp_network
# Required-Start:       $local_fs $remote_fs $network mysql
# Required-Stop:        $local_fs $remote_fs $network mysql
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    i-MSCP Network Traffic Logger
### END INIT INFO

# Note: do not modify any of these vars here, use /etc/default/$NAME instead

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DESC="i-MSCP Network Traffic Logger"
NAME=imscp_network
LFILE=/var/run/$NAME
IPTABLES=/usr/sbin/iptables
ENGINEPATH="/srv/www/imscp/engine"
ENGINETOOLSPATH=${ENGINEPATH}"/tools"
NETWORKCARDMANAGER="imscp-net-interfaces-mngr"
LOGDIR=/var/log/imscp
LOGFILE=${LOGDIR}/${NAME}.log
DIETIME=3

START=1

# To monitor more ports, edit SERVICES variable add your own ports
# (ftp, proxy, http, etc.)
#
# HTTP(S): 80 443
# POP3(S): 110 995
# IMAP4(S)): 143 993
# MAIL(S): 25 465 587
SERVICES="80 443 110 143 25 465 587 995 993"
# To monitor more outgoing ports, edit SERVICES_OUT variable add your own ports
# (mail, etc.)
#
# MAIL(S): 25 465 587
SERVICES_OUT="25 465 587"

umask 027

. /etc/rc.status

rc_reset

add_rules() {
	${IPTABLES} -N IMSCP_INPUT  2>> "$LOGFILE"
	${IPTABLES} -N IMSCP_OUTPUT 2>> "$LOGFILE"

	# All traffic should jump through IMSCP tables before anything else
	${IPTABLES} -I INPUT  -j IMSCP_INPUT  2>> "$LOGFILE"
	${IPTABLES} -I OUTPUT -j IMSCP_OUTPUT 2>> "$LOGFILE"

	# Services from matrix basically receiving data
	for PORT in $SERVICES; do
		${IPTABLES} -I IMSCP_INPUT  -p tcp --dport "$PORT" 2>> "$LOGFILE"
		${IPTABLES} -I IMSCP_OUTPUT -p tcp --sport "$PORT" 2>> "$LOGFILE"
	done

	# Services from matrix basically sending data
	for PORT in $SERVICES_OUT; do
		${IPTABLES} -I IMSCP_INPUT  -p tcp --sport "$PORT" 2>> "$LOGFILE"
		${IPTABLES} -I IMSCP_OUTPUT -p tcp --dport "$PORT" 2>> "$LOGFILE"
	done

	# Explicit return once done
	${IPTABLES} -A IMSCP_INPUT  -j RETURN
	${IPTABLES} -A IMSCP_OUTPUT -j RETURN

	# Touch lock file
	touch $LFILE
}

remove_rules() {
	${IPTABLES} -D INPUT  -j IMSCP_INPUT  2>> "$LOGFILE"
	${IPTABLES} -D OUTPUT -j IMSCP_OUTPUT 2>> "$LOGFILE"
	${IPTABLES} -F IMSCP_INPUT  2>> "$LOGFILE"
	${IPTABLES} -F IMSCP_OUTPUT 2>> "$LOGFILE"
	${IPTABLES} -X IMSCP_INPUT  2>> "$LOGFILE"
	${IPTABLES} -X IMSCP_OUTPUT 2>> "$LOGFILE"

	# Remove lock file
	rm $LFILE
}

add_interfaces() {
	${ENGINETOOLSPATH}/${NETWORKCARDMANAGER} start >${LOGDIR}/${NETWORKCARDMANAGER}.log 2>&1
}

remove_interfaces() {
	${ENGINETOOLSPATH}/${NETWORKCARDMANAGER} stop >${LOGDIR}/${NETWORKCARDMANAGER}.log 2>&1
}

case "$1" in
  start)
	echo -n "Starting $DESC" "$NAME"

	if [ -e "$LFILE" ]; then
		echo ""
		echo "Already loaded. Remove $LFILE if you think this an error."
	else
		add_interfaces
		add_rules
	fi

	rc_status -v
	;;
  stop)
	echo -n "Stopping $DESC" "$NAME"
	if [ -e "$LFILE" ]; then
		remove_rules
		remove_interfaces
	fi

	rc_status -v
	;;
  restart|force-reload)
	echo -n "Stopping $DESC" "$NAME"

	if [ -e "$LFILE" ]; then
		remove_rules
		remove_interfaces
		rc_status -v
		[ -n "$DIETIME" ] && sleep "$DIETIME"
	else
		true
		rc_status -v
	fi

	echo -n "Starting $DESC" "$NAME"

	add_interfaces
	add_rules

	rc_status -v

	;;
  status)
	echo -n "Checking status of $DESC" "$NAME"

	if [ ! -e "$LFILE" ]; then
	   echo " stopped"
	else
	   echo " started"
	fi

	echo ""
	;;
  *)
	echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

rc_exit
