#!/bin/sh

# i-MSCP - internet Multi Server Control Panel
# Copyright (C) 2010 - 2011 by internet Multi Server Control Panel
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

### BEGIN INIT INFO
# Provides:          imscp_daemon
# Required-Start:    $local_fs $remote_fs $network $syslog imscp_network
# Required-Stop:     $local_fs $remote_fs $network $syslog imscp_network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: i-MSCP GUI-Backend communication Daemon
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="i-MSCP GUI-Backend communication Daemon"
NAME=imscp_daemon
DAEMON=/srv/www/imscp/daemon/$NAME
PIDFILE=/var/run/$NAME.pid
DAEMON_ARGS=""
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

. /etc/rc.status

rc_reset

#
# Function that starts the daemon/service
#
do_start()
{
	startproc $DAEMON -- $DAEMON_ARGS
}

#
# Function that stops the daemon/service
#
do_stop()
{
	killproc -TERM $DAEMON
}

case "$1" in
  start)
	echo -n "Starting $DESC" "$NAME"
	do_start
	rc_status -v
	;;
  stop)
	echo -n "Stopping $DESC" "$NAME"
	do_stop
	rc_status -v
	;;
  status)
	checkproc "$DAEMON"
	rc_status -v
       ;;
  restart|force-reload)
	echo -n "Restarting $DESC" "$NAME"
	do_stop
	do_start
	rc_status -v
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac

rc_exit
